// Code generated by protoc-gen-go. DO NOT EDIT.
// source: function.proto

package function

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Kind int32

const (
	Kind_HTTP   Kind = 0
	Kind_CRON   Kind = 1
	Kind_STREAM Kind = 2
)

var Kind_name = map[int32]string{
	0: "HTTP",
	1: "CRON",
	2: "STREAM",
}

var Kind_value = map[string]int32{
	"HTTP":   0,
	"CRON":   1,
	"STREAM": 2,
}

func (x Kind) String() string {
	return proto.EnumName(Kind_name, int32(x))
}

func (Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8ac74addf543d91a, []int{0}
}

type Request struct {
	Kind                 Kind     `protobuf:"varint,1,opt,name=kind,proto3,enum=faast.Kind" json:"kind,omitempty"`
	Parameters           []byte   `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac74addf543d91a, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetKind() Kind {
	if m != nil {
		return m.Kind
	}
	return Kind_HTTP
}

func (m *Request) GetParameters() []byte {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type Response struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Parameters           []byte   `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ac74addf543d91a, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetParameters() []byte {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func init() {
	proto.RegisterEnum("faast.Kind", Kind_name, Kind_value)
	proto.RegisterType((*Request)(nil), "faast.Request")
	proto.RegisterType((*Response)(nil), "faast.Response")
}

func init() {
	proto.RegisterFile("function.proto", fileDescriptor_8ac74addf543d91a)
}

var fileDescriptor_8ac74addf543d91a = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2b, 0xcd, 0x4b,
	0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x4b, 0x4c, 0x2c,
	0x2e, 0x51, 0xf2, 0xe2, 0x62, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe7, 0x62,
	0xc9, 0xce, 0xcc, 0x4b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0xe2, 0xd6, 0x03, 0x2b, 0xd0,
	0xf3, 0xce, 0xcc, 0x4b, 0x09, 0x02, 0x4b, 0x08, 0xc9, 0x71, 0x71, 0x15, 0x24, 0x16, 0x25, 0xe6,
	0xa6, 0x96, 0xa4, 0x16, 0x15, 0x4b, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x04, 0x21, 0x89, 0x28, 0x39,
	0x70, 0x71, 0x04, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x70, 0xb1, 0xa6, 0x16,
	0x15, 0xe5, 0x17, 0x81, 0x4d, 0xe3, 0x0c, 0x82, 0x70, 0x08, 0x99, 0xa0, 0xa5, 0xc6, 0xc5, 0x02,
	0xb2, 0x4f, 0x88, 0x83, 0x8b, 0xc5, 0x23, 0x24, 0x24, 0x40, 0x80, 0x01, 0xc4, 0x72, 0x0e, 0xf2,
	0xf7, 0x13, 0x60, 0x14, 0xe2, 0xe2, 0x62, 0x0b, 0x0e, 0x09, 0x72, 0x75, 0xf4, 0x15, 0x60, 0x32,
	0xb2, 0xe0, 0xe2, 0x70, 0x83, 0x7a, 0x47, 0x48, 0x87, 0x8b, 0xdd, 0xb5, 0x22, 0x35, 0xb9, 0xb4,
	0x24, 0x55, 0x88, 0x0f, 0xea, 0x66, 0xa8, 0x8f, 0xa4, 0xf8, 0xe1, 0x7c, 0x88, 0xab, 0x94, 0x18,
	0x9c, 0xb8, 0xa2, 0x38, 0x60, 0x01, 0x91, 0xc4, 0x06, 0x0e, 0x09, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x2d, 0x35, 0xec, 0xc7, 0x1b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FunctionClient is the client API for Function service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FunctionClient interface {
	Execute(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type functionClient struct {
	cc grpc.ClientConnInterface
}

func NewFunctionClient(cc grpc.ClientConnInterface) FunctionClient {
	return &functionClient{cc}
}

func (c *functionClient) Execute(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/faast.Function/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FunctionServer is the server API for Function service.
type FunctionServer interface {
	Execute(context.Context, *Request) (*Response, error)
}

// UnimplementedFunctionServer can be embedded to have forward compatible implementations.
type UnimplementedFunctionServer struct {
}

func (*UnimplementedFunctionServer) Execute(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}

func RegisterFunctionServer(s *grpc.Server, srv FunctionServer) {
	s.RegisterService(&_Function_serviceDesc, srv)
}

func _Function_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faast.Function/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionServer).Execute(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Function_serviceDesc = grpc.ServiceDesc{
	ServiceName: "faast.Function",
	HandlerType: (*FunctionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _Function_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "function.proto",
}
